# Generated by Django 5.0.6 on 2024-07-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_order_invoice_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_ready',
            field=models.BooleanField(default=False),
        ),
    ]
