# Generated by Django 5.0.6 on 2024-07-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_order_invoice_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
