# Generated by Django 5.0.6 on 2024-07-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_invoice_order_alter_invoice_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_paid',
            field=models.BooleanField(default=False),
        ),
    ]
