# Generated by Django 5.0.6 on 2024-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_inbox_options_alter_inboxmessage_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='redirect',
            field=models.URLField(blank=True, null=True),
        ),
    ]
