# Generated by Django 5.0.6 on 2024-07-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_inboxmessage_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='redirect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
