# Generated by Django 5.0.6 on 2025-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auctionitem_auctionbid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionitem',
            options={},
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(blank=True, help_text='(500 character max)', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, help_text='(500 character max)', max_length=50, verbose_name='Description'),
        ),
    ]
