# Generated by Django 5.0.6 on 2025-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_auctionitem_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
