# Generated by Django 5.0.6 on 2025-01-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_auctionitem_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='available',
        ),
    ]
