# Generated by Django 5.0.6 on 2025-01-26 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_auctionitem_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
